name: 522-iris
channels:
  - conda-forge
dependencies:
  - altair-all
  - autograd
  - graphviz
  - ipykernel
  - ipython
  - jinja2
  - jupyterlab
  - lightgbm
  - matplotlib
  - nb_conda_kernels
  - numpy
  - pandas
  - panel
  - pip
  - plotly
  - python-graphviz
  - python==3.13.*
  - pytorch
  - requests
  - scikit-learn
  - seaborn
  - torchaudio
  - torchvision
  - vega_datasets
  - watchfiles
  - ucimlrepo