name: 522-iris
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - numpy=1.26.*
  - pandas=2.2.*
  - scikit-learn=1.5.*
  - matplotlib=3.8.*
  - seaborn=0.13.*
  - ipykernel
  - jupyterlab
  - altair=5.*
  - vega_datasets
  - plotly=5.*
  - graphviz
  - python-graphviz
  - requests
  - pip
  - nb_conda_kernels
  - panel
  - watchfiles
  - ucimlrepo
  - conda-lock = 3.0.4
  - pointblank
  - pip:
    - deepchecks
    - vegafusion

